package main

import (
	"log"

	pb "github.com/iammannat/go-grpc/proto"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

const (
	port = ":8080"
)

func main() {
	conn, err := grpc.NewClient("localhost"+port, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatalf("Did not connect: %v", err)
	}

	defer conn.Close()

	// This creates a client object that knows how to talk to your server. Auto-generated by gRPC from your .proto file
	client := pb.NewGreetServiceClient(conn)

	names := &pb.NamesList{
		Names: []string{"Mannat", "Alice", "Bob"},
	}

	// callSayHello(client)
	// callSayHelloServerStreaming(client, names)
	// callSayHelloClientStreaming(client, names)
	callSayHelloBidirectionalStreaming(client, names)
}
